### ISSUE TITLE
Broken link in setup page

### ISSUE THREAD

**Issue by scaminad** [RegardsOss/RegardsOss.github.io#4]
### Steps to reproduce bug
Go to https://regardsoss.github.io/docs/setup/
Click on the link in "You can now monitor and administrate the deployed stack thanks to cli commands as explained at Administration"

### Expected behavior
Should bring us to the Administration page

### Actual behavior
Page Not Found (link contains 2 times "/setup/")

### REGARDS version
REGARDS 1.0.0

### Browser
Chrome Version 58.0.3029.110 (64-bit)

*Note : If you have file attachments, provide them*

**Comment by sebastienbinda** [comment]
This commit should fix the issue once the site is rebuilt https://github.com/RegardsOss/RegardsOss.github.io/commit/9cce2cb80c088ae858b74be801e890ce4fe87643

**Comment by scaminad** [comment]
Solved. Thank you.
